In [ ]:

!pip install -U scikit-learn





[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: C:\Users\anjal\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [68]:
import pandas as pd
from numpy import set_printoptions
from sklearn import preprocessing

# Load your dataset
df = pd.read_csv("masala_dataset.csv")
numeric_df = df.select_dtypes(include=['number'])

data_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
data_rescaled = data_scaler.fit_transform(numeric_df)
set_printoptions(precision=1)
print("\nscaled data:\n",  data_rescaled[0:10])


scaled data:
 [[0.9 0.5 0.4 0.  0.5]
 [0.7 0.9 0.9 0.1 0.3]
 [0.4 0.6 0.9 0.4 0.1]
 [0.4 0.  0.2 0.5 0.2]
 [0.8 0.7 0.3 0.7 0.3]
 [0.8 0.8 0.2 0.5 0.8]
 [0.6 0.2 0.  0.3 0.9]
 [0.9 0.  0.4 0.9 0.5]
 [0.9 0.8 0.5 0.9 0.8]
 [0.2 0.5 0.  0.5 0.4]]
