lets a student data in python

In [ ]:
name = "alice"
age  = 18
GPA = 3.78
plays_volleyball = True

print(name)

alice


alice


In [ ]:
print(name, age, GPA,  plays_volleyball)

alice 18 3.78 True


In [ ]:
GPA = GPA + 0.07

print(name, age, GPA,  plays_volleyball)

alice 18 3.8499999999999996 True


lets try and print the student information in a more meaningful manner

In [ ]:
print(f"The student name is {name} and they are {age} years old.")

The student name is alice and they are 18 years old.


lets calculate the alice's age in 15 years

In [ ]:
age = age + 15
print(f"The student name is {name} and they are {age} years old in 15 years.")

The student name is alice and they are 33 years old in 15 years.


In [ ]:
sports = ["volleyball", "netball", "touch rugby", "cross country"]
sports[0]

'volleyball'

In [ ]:
sports.append("cricket")

print("Alice is currently playing:", sports)

Alice is currently playing: ['volleyball', 'netball', 'touch rugby', 'cross country', 'cricket']


##lists in python


In [ ]:
sports[0:3]

['volleyball', 'netball', 'touch rugby']

lets see the **last 3 sports** alice is playing

In [ ]:
sports[2:]

['touch rugby', 'cross country', 'cricket']

## calculating letter grade

- 2 or under D
- 3 or under C
- 3.8 or under B
- Above 3.8 A

In [12]:
Student_gpa = float(input("what is your GPA? "))
if Student_gpa <= 2:
    letter_grade = "D"
elif Student_gpa <= 3:
    letter_grade = "C"
elif Student_gpa <= 3.8:
    letter_grade = "B"
else:
    letter_grade = "A"
print(f"student's letter grade is {letter_grade}.")
   

KeyboardInterrupt: Interrupted by user

**Dictionaries in python**

##extracting keys


In [ ]:
fruit ={"apple": 2.5, "banana": 1.2, "orange": 3.0}
fruit.keys()

dict_keys(['apple', 'banana', 'orange'])

##extracting values

In [ ]:
fruit = {"apple": 2.5, "banana": 1.2, "orange": 3.0}
fruit.values()

dict_values([2.5, 1.2, 3.0])

##extracting items

In [ ]:
fruit.items()

dict_items([('apple', 2.5), ('banana', 1.2), ('orange', 3.0)])

##adding new elements to dictionary

In [ ]:

fruit["grape"] = 4.0
fruit


{'apple': 2.5, 'banana': 1.2, 'orange': 3.0, 'grape': 4.0}

##changing an existing element

In [ ]:
fruit = {"apple": 2.5, "banana": 1.2, "orange": 3.0}
fruit["banana"] = 1.5
fruit


{'apple': 2.5, 'banana': 1.5, 'orange': 3.0}

##update one dictionary's element with another

In [ ]:
fruit1 ={"apple": 2.5, "banana": 1.2}
fruit2 ={"orange": 3.0, "grape": 4.0}
fruit1.update(fruit2)
print(fruit1)


{'apple': 2.5, 'banana': 1.2, 'orange': 3.0, 'grape': 4.0}


##popping an element

In [ ]:
fruit= {"apple": 2.5, "banana": 1.2, "orange": 3.0}
fruit.pop("banana")
print (fruit)

{'apple': 2.5, 'orange': 3.0}


##sets in python

In [ ]:
S1= {1,'poorna',1 ,'poorna'}
S1


{1, 'poorna'}

##adding a new element

In [ ]:
S1 = {1, "a", True, 2, "b", False}
S1.add("hello")
S1

{1, 2, False, 'a', 'b', 'hello'}

##updating multiple elements

In [ ]:
S1= {1, "a", True, 2, "b", False}
S1.update([10,20,30])
S1

{1, 10, 2, 20, 30, False, 'a', 'b'}

##removing an element

In [ ]:
S1= {1, "a", True, 2, "b", False}
S1.remove("b")
S1


{1, 2, False, 'a'}

##copying array in python


In [ ]:
from numpy import*
arr = array([1,2,3,4,5])
arr = arr + 5
print(arr)

[ 6  7  8  9 10]


In [ ]:
from numpy import*
arr1 = array([1,2,3,4,5])
arr2 = arr1.view()
print(arr1)
print(arr2)

[1 2 3 4 5]
[1 2 3 4 5]


##vectorisedoperation

In [ ]:
from numpy import*
arr1= array([1,2,3,4,5])
arr2= array([5,4,3,2,1])
arr3 = arr1 + arr2
print(arr3)

[6 6 6 6 6]


##concatenate

In [ ]:
from numpy import*
arr1=([1,2,3,4,5])
arr2 =([6,7,8,9,10])
print(concatenate([arr1,arr2]))

[ 1  2  3  4  5  6  7  8  9 10]


##function arguments in python

In [ ]:
def update(x):
    x=8
    print(x)